### ISSUE TITLE
Hyperparameters of other datasets

### ISSUE THREAD

**Issue by JhuoW** [kleincup/MGMN#1]
Hi, 
It's a good work. Could you provide hyperparameters of other datasets such as LINUX of GED pred

**Comment by ryderling** [comment]
Thanks for your attention. 
As for your question, I do not know what hyperparameters of datasets you want to know.
Could you be more detailed?
In fact, all hyperparameters of our models are given in the paper, and all benchmark datasets like LINUX are used as the original paper.
