### ISSUE TITLE
为什么在回归任务中，基线模型的效果跟基线模型原文不符合？

### ISSUE THREAD

**Issue by haocibuni** [kleincup/MGMN#2]

**Comment by ryderling** [comment]
We repeat all experiments (including all baselines and our models) five times and report the mean and standard deviation of experimental results.
Detailed experimental settings for baselines can be found in Appendix B.

**Comment by haocibuni** [comment]
请问是什么原因让graphsim的基线和原文差距这么大？

**Comment by ryderling** [comment]
We just run the original source code of all baselines and report the experimental results.
For the issues related to graphsim, perhaps you need to run it yourself or ask for help from its authors.

**Comment by haocibuni** [comment]
谢谢回答！
